name: Build and Deploy

on:
  push:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install Dependencies
        run: npm install --legacy-peer-deps --force

      - name: Build and Deploy
        env:
          NODE_ENV: production
        run: npm run build

      - name: Serve
        env:
          NODE_ENV: production
        run: npm run serve
